//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAnketApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anket
    {
        public int anket_id { get; set; }
        public Nullable<int> kullanici_id_anket { get; set; }
        public Nullable<int> kategori_id_anket { get; set; }
        public Nullable<int> soru_id_anket { get; set; }
        public Nullable<int> cevap_id_anket { get; set; }
        public Nullable<bool> yayin_durumu { get; set; }
    
        public virtual Cevap Cevap { get; set; }
        public virtual Kategori Kategori { get; set; }
        public virtual Soru Soru { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
