//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAnketApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class buAnket
    {
        public int id { get; set; }
        public string kategori { get; set; }
        public string soru { get; set; }
        public string cevaplar { get; set; }
        public string cevap1 { get; set; }
        public string cevap2 { get; set; }
    
        public virtual buAnket buAnket1 { get; set; }
    }
}
